/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kue_rumah;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author acer
 */
public class Menu extends javax.swing.JFrame {
    Connection con = null;
    Statement st=null;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnspiku = new javax.swing.JButton();
        btngulung = new javax.swing.JButton();
        btncaramel = new javax.swing.JButton();
        btnkukis = new javax.swing.JButton();
        btnbikang = new javax.swing.JButton();
        btnpastel = new javax.swing.JButton();
        btnlemper = new javax.swing.JButton();
        btnlumpur = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnultah = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cboTglpemes = new javax.swing.JComboBox<>();
        cboBlnpemes = new javax.swing.JComboBox<>();
        cboThnpemes = new javax.swing.JComboBox<>();
        txtAlamat = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtHarga1 = new javax.swing.JTextField();
        txtJumlah1 = new javax.swing.JTextField();
        txtJumlah2 = new javax.swing.JTextField();
        txtHarga3 = new javax.swing.JTextField();
        txtJumlah3 = new javax.swing.JTextField();
        txtHarga2 = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cboPembayaran = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cboTglpengam = new javax.swing.JComboBox<>();
        cboBlnpengam = new javax.swing.JComboBox<>();
        cboThnpengam = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        cboPengambilan = new javax.swing.JComboBox<>();
        btnsimpan = new javax.swing.JButton();
        btnbersih = new javax.swing.JButton();
        btnhapusdata = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnhitung = new javax.swing.JButton();
        txtKue1 = new javax.swing.JTextField();
        txtKue2 = new javax.swing.JTextField();
        txtKue3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kue_rumah/logo...PNG"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Forte", 0, 48)); // NOI18N
        jLabel2.setText("KUE RUMAHAN");

        jLabel3.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        jLabel3.setText("Daftar Kue");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kue_rumah/1.spiku.PNG"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kue_rumah/2.rotigulung.PNG"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kue_rumah/3.caramel.PNG"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kue_rumah/4.kukis.PNG"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kue_rumah/5.bikang.PNG"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kue_rumah/6.pastel.PNG"))); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kue_rumah/7.lemper.PNG"))); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kue_rumah/8.limpur.PNG"))); // NOI18N
        jLabel11.setText("jLabel11");

        btnspiku.setText("Spiku");
        btnspiku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnspikuActionPerformed(evt);
            }
        });

        btngulung.setText("Gulung");
        btngulung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngulungActionPerformed(evt);
            }
        });

        btncaramel.setText("Caramel");
        btncaramel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaramelActionPerformed(evt);
            }
        });

        btnkukis.setText("Pukis");
        btnkukis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkukisActionPerformed(evt);
            }
        });

        btnbikang.setText("Bikang");
        btnbikang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbikangActionPerformed(evt);
            }
        });

        btnpastel.setText("Pastel");
        btnpastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpastelActionPerformed(evt);
            }
        });

        btnlemper.setText("Lemper");
        btnlemper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlemperActionPerformed(evt);
            }
        });

        btnlumpur.setText("Lumpur");
        btnlumpur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlumpurActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kue_rumah/9.ultah.PNG"))); // NOI18N
        jLabel12.setText("jLabel12");

        btnultah.setText("Ultah");
        btnultah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnultahActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        jLabel13.setText("Data Pembeli");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Tanggal Pemesanan");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Alamat");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Nama");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("NoTelp");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Nama Kue");

        jLabel19.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        jLabel19.setText("Data Pesanan");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("Harga dan Jumlah");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Total");

        cboTglpemes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cboBlnpemes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cboThnpemes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        txtAlamat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtTelp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpActionPerformed(evt);
            }
        });

        txtNama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtHarga1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtJumlah1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtJumlah2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtJumlah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlah2ActionPerformed(evt);
            }
        });

        txtHarga3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtHarga3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHarga3ActionPerformed(evt);
            }
        });

        txtJumlah3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtHarga2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtTotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Pembayaran");

        cboPembayaran.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cboPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Transfer", "Tunai" }));
        cboPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPembayaranActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Tanggal Pengambilan");

        cboTglpengam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cboBlnpengam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cboThnpengam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("Pengambilan");

        cboPengambilan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cboPengambilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Ambil Sendiri", "Jasa Antar" }));

        btnsimpan.setBackground(new java.awt.Color(102, 255, 51));
        btnsimpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(51, 51, 51));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbersih.setBackground(new java.awt.Color(255, 153, 0));
        btnbersih.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnbersih.setText("Bersih");
        btnbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihActionPerformed(evt);
            }
        });

        btnhapusdata.setBackground(new java.awt.Color(255, 153, 0));
        btnhapusdata.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnhapusdata.setText("Hapus Data");
        btnhapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusdataActionPerformed(evt);
            }
        });

        btnkeluar.setBackground(new java.awt.Color(204, 0, 0));
        btnkeluar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btnhitung.setBackground(new java.awt.Color(51, 51, 255));
        btnhitung.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        txtKue1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtKue2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtKue3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(btnspiku)
                                        .addGap(122, 122, 122)
                                        .addComponent(btngulung)
                                        .addGap(109, 109, 109)
                                        .addComponent(btnpastel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(btncaramel)
                                        .addGap(116, 116, 116)
                                        .addComponent(btnkukis)
                                        .addGap(118, 118, 118)
                                        .addComponent(btnbikang)))
                                .addGap(56, 56, 56))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnlemper)
                                .addGap(112, 112, 112)
                                .addComponent(btnlumpur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnultah)
                                .addGap(114, 114, 114)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel19)
                                .addGap(115, 115, 115))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtKue2)
                                    .addComponent(cboPengambilan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cboTglpengam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboBlnpengam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboThnpengam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                        .addComponent(txtJumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtJumlah1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJumlah2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(btnhitung))
                                    .addComponent(cboPembayaran, javax.swing.GroupLayout.Alignment.LEADING, 0, 143, Short.MAX_VALUE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKue1)
                                    .addComponent(txtKue3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cboTglpemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboBlnpemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboThnpemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNama)
                                    .addComponent(txtTelp))))))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbersih, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapusdata)
                    .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnspiku)
                                    .addComponent(btngulung)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnpastel)
                                .addGap(3, 3, 3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cboTglpemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboBlnpemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboThnpemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtKue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtKue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnhitung)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(cboTglpengam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboBlnpengam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboThnpengam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(cboPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncaramel)
                            .addComponent(btnkukis)
                            .addComponent(btnbikang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnlemper)
                                .addComponent(btnlumpur))
                            .addComponent(btnultah)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtJumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsimpan))
                        .addGap(18, 18, 18)
                        .addComponent(btnbersih)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapusdata)
                        .addGap(18, 18, 18)
                        .addComponent(btnkeluar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHarga3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHarga3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHarga3ActionPerformed

    private void txtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpActionPerformed

    private void cboPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPembayaranActionPerformed

    private void txtJumlah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlah2ActionPerformed

    private void btnbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihActionPerformed
        txtNama.setText("");
        txtAlamat.setText("");
        txtHarga1.setText("");
        txtHarga2.setText("");
        txtHarga3.setText("");
        txtJumlah1.setText("");
        txtJumlah2.setText("");
        txtJumlah3.setText("");
        txtKue1.setText("");
        txtKue2.setText("");
        txtKue3.setText("");
        txtTelp.setText("");
        txtTotal.setText("");
        cboPengambilan.setSelectedIndex(0);
        cboTglpemes.setSelectedIndex(0);
        cboPembayaran.setSelectedIndex(0);
        cboBlnpengam.setSelectedIndex(0);
        cboBlnpemes.setSelectedIndex(0);
        cboTglpengam.setSelectedIndex(0);
        cboThnpemes.setSelectedIndex(0);
        cboThnpengam.setSelectedIndex(0);
    }//GEN-LAST:event_btnbersihActionPerformed

    private void btnspikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnspikuActionPerformed
        txtKue1.setText("Spiku");
        txtHarga1.setText("25000");
    }//GEN-LAST:event_btnspikuActionPerformed

    private void btngulungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngulungActionPerformed
        txtKue1.setText("Gulung");
        txtHarga1.setText("25000");
    }//GEN-LAST:event_btngulungActionPerformed

    private void btnpastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpastelActionPerformed
        txtKue1.setText("Pastel");
        txtHarga1.setText("2500");
    }//GEN-LAST:event_btnpastelActionPerformed

    private void btncaramelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaramelActionPerformed
        txtKue2.setText("Caramel");
        txtHarga2.setText("30000");
    }//GEN-LAST:event_btncaramelActionPerformed

    private void btnkukisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkukisActionPerformed
        txtKue2.setText("Kukis");
        txtHarga2.setText("2000");
    }//GEN-LAST:event_btnkukisActionPerformed

    private void btnbikangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbikangActionPerformed
        txtKue2.setText("Bikang");
        txtHarga2.setText("2500");
    }//GEN-LAST:event_btnbikangActionPerformed

    private void btnlemperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlemperActionPerformed
        txtKue3.setText("Lemper");
        txtHarga3.setText("3000");
    }//GEN-LAST:event_btnlemperActionPerformed

    private void btnlumpurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlumpurActionPerformed
        txtKue3.setText("Lumpur");
        txtHarga3.setText("2500");
    }//GEN-LAST:event_btnlumpurActionPerformed

    private void btnultahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnultahActionPerformed
        txtKue3.setText("Ultah");
        txtHarga3.setText("100000");
    }//GEN-LAST:event_btnultahActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        int harga1=Integer.parseInt(txtHarga1.getText());
        int harga2=Integer.parseInt(txtHarga2.getText());
        int harga3=Integer.parseInt(txtHarga3.getText());
        int jumlah1=Integer.parseInt(txtJumlah1.getText());
        int jumlah2=Integer.parseInt(txtJumlah2.getText());
        int jumlah3=Integer.parseInt(txtJumlah3.getText());
        int total, total1, total2,total2a, total3;
        total1= harga1*jumlah1;
        total2= harga2*jumlah2;
        total2a= total1 + total2;
        total3= harga3*jumlah3;
        total= total1 + total2 + total3;
        txtTotal.setText(""+ total1);
        txtTotal.setText(""+ total2a);
        txtTotal.setText(""+ total);
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        
        try{
            if (txtNama.getText().equals("")|| txtTotal.getText().equals("")||
                    cboPengambilan.getSelectedItem().equals("")){
                JOptionPane.showConfirmDialog(this," Data tidak boleh kosong","pesan", JOptionPane.ERROR_MESSAGE);
                
            }
            else{
                koneksi ObjKoneksi = new koneksi();
                Connection con = ObjKoneksi.bukaKoneksi();
                Statement st = con.createStatement();
                String simpan ="INSERT INTO pemesanan VALUES ('"+cboTglpemes.getSelectedItem()+"','"+cboBlnpemes.getSelectedItem()
                        +"','"+cboThnpemes.getSelectedItem()+"','"+txtNama.getText()+"','" +txtAlamat.getText()+"','"+txtTelp.getText()
                        +"','"+txtKue1.getText()+"','"+txtKue2.getText()+"','"+txtKue3.getText()+"','"+txtHarga1.getText()
                        +"','"+txtHarga2.getText()+"','"+txtHarga3.getText()+"','"+txtJumlah1.getText()+"','"+txtJumlah2.getText()
                        +"','"+txtJumlah3.getText()+"','"+txtTotal.getText()+"','"+cboPembayaran.getSelectedItem()
                        +"','"+cboTglpengam.getSelectedItem()+"','"+cboBlnpengam.getSelectedItem()
                        +"','"+cboThnpengam.getSelectedItem()+"','"+cboPengambilan.getSelectedItem()+"')";
                st=con.createStatement();
                int SA =st.executeUpdate(simpan);
                JOptionPane.showConfirmDialog(this, "Semua Data Sudah Tersimpan");
                this.setVisible(false);
                new Menu ().setVisible(true);
            }
        }
        catch (Exception e){
            JOptionPane.showConfirmDialog(this, "Semua Data Tidak Bisa Tersimpan","pesan",
                    JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusdataActionPerformed
        try{
        koneksi ObjKoneksi = new koneksi();
        Connection con = ObjKoneksi.bukaKoneksi();
        Statement st = con.createStatement();
        String sql = "delete from pemesanan where nama = '"+txtNama.getText()+"' ";
        int row = st.executeUpdate(sql);
        if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah dihapus dari " +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
               
                con.close();

                }
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Data tidak dihapus","infomasi",JOptionPane.
                INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnhapusdataActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        this.setVisible(false);
        new login ().setVisible(true);
//System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbersih;
    private javax.swing.JButton btnbikang;
    private javax.swing.JButton btncaramel;
    private javax.swing.JButton btngulung;
    private javax.swing.JButton btnhapusdata;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnkukis;
    private javax.swing.JButton btnlemper;
    private javax.swing.JButton btnlumpur;
    private javax.swing.JButton btnpastel;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnspiku;
    private javax.swing.JButton btnultah;
    private javax.swing.JComboBox<String> cboBlnpemes;
    private javax.swing.JComboBox<String> cboBlnpengam;
    private javax.swing.JComboBox<String> cboPembayaran;
    private javax.swing.JComboBox<String> cboPengambilan;
    private javax.swing.JComboBox<String> cboTglpemes;
    private javax.swing.JComboBox<String> cboTglpengam;
    private javax.swing.JComboBox<String> cboThnpemes;
    private javax.swing.JComboBox<String> cboThnpengam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtHarga1;
    private javax.swing.JTextField txtHarga2;
    private javax.swing.JTextField txtHarga3;
    private javax.swing.JTextField txtJumlah1;
    private javax.swing.JTextField txtJumlah2;
    private javax.swing.JTextField txtJumlah3;
    private javax.swing.JTextField txtKue1;
    private javax.swing.JTextField txtKue2;
    private javax.swing.JTextField txtKue3;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
